name: Deploy to GitHub Pages

on:
  push:
    branches: [ gh-pages ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Install Trunk
      uses: jetli/trunk-action@v0.5.0
      with:
        version: 'latest'

    - name: Build
      run: trunk build --release --public-url /hosting/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

